### ISSUE TITLE
Default repo for new issue reporting in Git

### ISSUE THREAD

**Issue by pushkar-promptmule** [PromptMuleCentral/reported-list#2]
Currently, when a new issue is raised through /raise-issue api, the same gets created in [fetch_user_prompts](https://github.com/PromptMuleCentral/fetch_user_prompts/issues) repo.
Please use this repo for creating new issues - https://github.com/PromptMuleCentral/reported-list

This is a new public repo that's been created.

**Comment by Promptmule-harsh** [comment]
Validated 



[Default repo for new issue reporting in Git#2.pdf](https://github.com/PromptMuleCentral/reported-list/files/12495604/Default.repo.for.new.issue.reporting.in.Git.2.pdf)
